### hello world
GET http://localhost:8000/

### fetch product list
GET http://localhost:8000/products

### create product
POST http://localhost:8000/products
Content-Type: application/json

{
  "name": "Teh Pucuk",
  "category": "Minuman",
  "qty": 5,
  "price" : 7500
}

###get product by id
GET http://localhost:8000/products/16

### update product
PUT http://localhost:8000/products/9
Content-Type: application/json

{
  "name": "Teh Pucuk",
  "category": "Minuman",
  "qty": 4,
  "price" : 1500
}

### delete user
DELETE http://localhost:8000/products/11

### soft delete user
PUT http://localhost:8000/products/soft-delete/12